server:
  port: 8888
spring:
  application:
    name: pped-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: PPED_GROUP
    gateway:
      routes: #数组形式
        - id: nacos #路由唯一标识
          uri: lb://pped-nacos #想要转发到的地址，从nacos注册中心上拉取，lb：负载均衡轮询
          predicates: #断言 配置哪个路径才转发
            - Path=/nacos/**
          filters:
            - StripPrefix=1 #去掉第一层前缀
        - id: sentinel
          uri: lb://pped-sentinel
          predicates:
            - Path=/sentinel/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


